ident: workflow
name: Workflow
name_cn: 工作流
slug: /workflow
items:
  - https://github.com/apache/airflow
  - https://github.com/apache/nifi
  - https://github.com/spotify/luigi
  - https://github.com/azkaban/azkaban
  - https://github.com/apache/oozie
  - https://github.com/Netflix/conductor
  - https://github.com/dagster-io/dagster
  - https://github.com/PrefectHQ/prefect
  - https://github.com/kubeflow/pipelines
  - https://github.com/backstage/backstage
  - https://github.com/PipedreamHQ/pipedream
  - https://github.com/camunda/camunda-bpm-platform
  - https://github.com/sartography/SpiffWorkflow
